#配置端口
server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wzcoupon?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  redis:
    host: 47.101.199.151
    port: 6380
    database: 0
    password: Bl123456@
    jedis:
      pool:
        min-idle: 1
        max-idle: 8

mybatis:
  type-aliases-package: com.gxa.boot338.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    return-instance-for-empty-row: true
